[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "P4PNodeGossiper"
dynamic = ["version"]
description = "A gossiper for finding nodes"
dependencies = [
    "P4PCore @ git+https://github.com/stsaria/P4PCore.git"
]
license = { file = "LICENSE" }
requires-python = ">=3.13"

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
version_scheme = "guess-next-dev"